import "styles/globals.scss";
import "icon/index.scss";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import Navbar from "components/Navbar/Navbar";
import Footer from "components/Footer/Footer";
import GotoTop from "components/GotoTop/GotoTop";
import { FC, useEffect } from "react";
import { NextUIProvider, Container } from "@nextui-org/react";

const MyApp: FC<AppProps> = ({ Component, pageProps }) => {
  useEffect(() => {
    document.querySelector("body").style.backgroundImage =
      "url('/images/bg.png')";
  }, []);

  return (
    <NextUIProvider>
      <Head>
        <title>Paff manga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container-global-class">
        <Navbar />
        <Container lg>
          <Component {...pageProps} className="global-class" />
        </Container>
        <Footer />
        <GotoTop />
      </div>
    </NextUIProvider>
  );
};

export default MyApp;
